"""core: vocabulary, dimensions, specs, protocols, verdicts, and intervals.

The foundation layer. Imports nothing else from axiom; depends only on
numpy, scipy, and pydantic. Everything here is a ``Spec`` or a protocol.
"""

from axiom.core.dimensions import (
    BASES,
    UNITS,
    BaseRegistry,
    D,
    Dimension,
    DimensionError,
    UndeclaredBaseError,
    UnitConversionError,
    UnitSystem,
    dimensionless,
)
from axiom.core.entities import (
    Covariate,
    Dose,
    Entity,
    EntityName,
    Intervention,
    Outcome,
    Population,
    TimeWindow,
    Treatment,
    UndimensionedWarning,
    Unit,
    dimension_of,
)
from axiom.core.expr import (
    Add,
    Apply,
    ApplyFn,
    Const,
    Convolve,
    Data,
    Div,
    Equation,
    Expr,
    Link,
    LinkFn,
    Model,
    Mul,
    ODESystem,
    Opaque,
    Param,
    Pow,
    Prior,
    System,
    children,
    data_names,
    node_path,
    params,
    walk,
)
from axiom.core.interpret import (
    OpaqueFn,
    OpaqueRegistry,
    causal_convolve,
    check,
    dimension,
    latex,
    latex_or_unsupported,
    value,
)
from axiom.core.intervals import Interval, Summary, eti, hdi, interval, summarize, wald
from axiom.core.posterior import Posterior
from axiom.core.protocols import (
    Capability,
    PredictiveDraws,
    SupportsForward,
    SupportsIntervention,
    SupportsPosterior,
    missing_capabilities,
)
from axiom.core.result import Blocked, Failure, NonEmptyStr, Unsupported, Unverified, is_failure
from axiom.core.spec import (
    SchemaVersionError,
    Spec,
    SpecDiff,
    SpecError,
    UnknownSpecError,
    load_spec,
    spec_type_name,
)
from axiom.core.stats import (
    AcceptanceRegion,
    clopper_pearson,
    effective_sample_size,
    mc_standard_error,
    z_score,
)
from axiom.core.verdict import Assumption, LedgerLine, Verdict

__all__ = [
    "BASES",
    "D",
    "UNITS",
    "AcceptanceRegion",
    "Add",
    "Apply",
    "ApplyFn",
    "Assumption",
    "BaseRegistry",
    "Blocked",
    "Capability",
    "Const",
    "Convolve",
    "Covariate",
    "Data",
    "Dimension",
    "DimensionError",
    "Div",
    "Dose",
    "Entity",
    "EntityName",
    "Equation",
    "Expr",
    "Failure",
    "Intervention",
    "Interval",
    "LedgerLine",
    "Link",
    "LinkFn",
    "Model",
    "Mul",
    "NonEmptyStr",
    "ODESystem",
    "Opaque",
    "OpaqueFn",
    "OpaqueRegistry",
    "Outcome",
    "Param",
    "Population",
    "Posterior",
    "Pow",
    "PredictiveDraws",
    "Prior",
    "SchemaVersionError",
    "Spec",
    "SpecDiff",
    "SpecError",
    "Summary",
    "SupportsForward",
    "SupportsIntervention",
    "System",
    "SupportsPosterior",
    "TimeWindow",
    "Treatment",
    "UndeclaredBaseError",
    "UndimensionedWarning",
    "Unit",
    "UnitConversionError",
    "UnitSystem",
    "UnknownSpecError",
    "Unsupported",
    "Unverified",
    "Verdict",
    "causal_convolve",
    "check",
    "children",
    "clopper_pearson",
    "data_names",
    "dimension",
    "dimension_of",
    "dimensionless",
    "effective_sample_size",
    "eti",
    "hdi",
    "interval",
    "is_failure",
    "latex",
    "latex_or_unsupported",
    "load_spec",
    "mc_standard_error",
    "missing_capabilities",
    "node_path",
    "params",
    "spec_type_name",
    "summarize",
    "value",
    "wald",
    "walk",
    "z_score",
]
