"""Trust machinery: SBC, coverage, posterior predictive and residual checks, sensitivity to
unobserved confounding, weak identification, prior-to-posterior learning, specification curves,
refutation, and rolling-origin backtests.

See ``docs/plan/03-roadmap.md`` (Phase 8) and ``nbs/diagnose/``.
"""

from __future__ import annotations

from axiom.diagnose.backtest import (
    Backtest,
    FrozenPredictor,
    HorizonScore,
    OriginFailure,
    OriginForecast,
    crps,
    forecast,
    freeze,
    rolling_origin,
    training_panel,
)
from axiom.diagnose.coverage import (
    CoverageResult,
    EstimandCoverage,
    EstimandCoverageResult,
    Fitter,
    ParameterCoverage,
    SupportsWorld,
    WorldFactory,
    WorldView,
    coverage,
    estimand_coverage,
    misspecify,
    truth_producer,
)
from axiom.diagnose.learning import (
    LearningReport,
    ParameterLearning,
    bhattacharyya,
    learning,
)
from axiom.diagnose.ppc import (
    DEFAULT_STATISTICS,
    PPCResult,
    Statistic,
    StatisticCheck,
    posterior_predictive,
)
from axiom.diagnose.refute import (
    Refutation,
    RefutationKind,
    added_noise,
    permutation,
    placebo_treatment,
    random_subset,
)
from axiom.diagnose.residuals import (
    ResidualReport,
    ResidualTest,
    UnitResiduals,
    residuals,
)
from axiom.diagnose.sbc import (
    ParameterRanks,
    SBCResult,
    SBCSpec,
    Simulator,
    default_bins,
    draw_prior,
    rank_uniformity,
    sbc,
    sbc_pool,
    sbc_surface,
    simulate_outcome,
)
from axiom.diagnose.sensitivity import (
    Benchmark,
    BiasBounds,
    RobustnessValue,
    ShiftedPosterior,
    TippingPoint,
    benchmark,
    bias_bounds,
    partial_r2,
    robustness_value,
    shift_posterior,
    tipping_point,
)
from axiom.diagnose.spec_curve import (
    FitSettings,
    SpecCurve,
    SpecCurveSummary,
    SpecificationAxis,
    SpecOption,
    SpecRow,
    apply_option,
    default_estimand,
    realized_point,
    specification_curve,
)
from axiom.diagnose.surface_prior import (
    ExpectedSign,
    PriorPredictive,
    prior_predictive,
)
from axiom.diagnose.weak_id import (
    WeakIdReport,
    prior_moments,
    weak_identification,
)

__all__ = [
    "Backtest",
    "Benchmark",
    "BiasBounds",
    "CoverageResult",
    "DEFAULT_STATISTICS",
    "EstimandCoverage",
    "EstimandCoverageResult",
    "ExpectedSign",
    "FitSettings",
    "Fitter",
    "FrozenPredictor",
    "HorizonScore",
    "LearningReport",
    "OriginFailure",
    "OriginForecast",
    "PPCResult",
    "ParameterCoverage",
    "ParameterLearning",
    "ParameterRanks",
    "PriorPredictive",
    "Refutation",
    "RefutationKind",
    "ResidualReport",
    "ResidualTest",
    "RobustnessValue",
    "SBCResult",
    "SBCSpec",
    "ShiftedPosterior",
    "Simulator",
    "SpecCurve",
    "SpecCurveSummary",
    "SpecOption",
    "SpecRow",
    "SpecificationAxis",
    "Statistic",
    "StatisticCheck",
    "SupportsWorld",
    "TippingPoint",
    "UnitResiduals",
    "WeakIdReport",
    "WorldFactory",
    "WorldView",
    "added_noise",
    "apply_option",
    "benchmark",
    "bhattacharyya",
    "bias_bounds",
    "coverage",
    "crps",
    "default_bins",
    "default_estimand",
    "draw_prior",
    "estimand_coverage",
    "forecast",
    "freeze",
    "learning",
    "misspecify",
    "partial_r2",
    "permutation",
    "placebo_treatment",
    "posterior_predictive",
    "prior_moments",
    "prior_predictive",
    "random_subset",
    "rank_uniformity",
    "realized_point",
    "residuals",
    "robustness_value",
    "rolling_origin",
    "sbc",
    "sbc_pool",
    "sbc_surface",
    "shift_posterior",
    "simulate_outcome",
    "specification_curve",
    "tipping_point",
    "training_panel",
    "truth_producer",
    "weak_identification",
]
