"""surface: dose-response kernels, carryover, nuisance terms, designs, ascent.

Every kernel is built from ``axiom.core`` expression nodes and evaluated by
the interpreters — there is one ``forward()``. No sampler is imported here;
fitting goes through ``axiom.infer``.
"""

from axiom.surface.ascent import (
    AscentPath,
    Method,
    StationaryPoint,
    canonical_analysis,
    gradient,
    hessian,
    steepest_ascent,
)
from axiom.surface.carryover import (
    CARRYOVERS,
    AnyCarryover,
    CarryoverKernel,
    CarryoverRole,
    DelayedCarryover,
    GeometricCarryover,
    NoCarryover,
    WeibullCarryover,
    carryover_from_name,
)
from axiom.surface.design import (
    Bounds,
    Criterion,
    Design,
    a_criterion,
    bayesian_criterion,
    box_behnken,
    central_composite,
    d_criterion,
    defining_relation,
    e_criterion,
    equal_spacing,
    fractional_factorial,
    full_factorial,
    latin_hypercube,
    optimal_exchange,
)
from axiom.surface.forward import (
    GRID_VERSION,
    MarginalHorizon,
    counterfactual_doses,
    forward,
    marginal,
    marginal_expr,
    marginal_total,
    predict,
    predict_marginal,
)
from axiom.surface.frontier import Frontier, frontier
from axiom.surface.kernels import (
    KERNELS,
    AnyKernel,
    ExponentialKernel,
    HillKernel,
    KernelRole,
    LinearKernel,
    LogisticKernel,
    PowerKernel,
    ResponseKernel,
    kernel_from_name,
)
from axiom.surface.linearize import (
    check_linearization,
    column_names,
    design_matrix,
    linear_coefficients,
)
from axiom.surface.model import (
    FitResult,
    InterceptKind,
    ParameterRole,
    Surface,
    SurfaceSpec,
    build,
    fit,
    interaction_name,
    parameter_roles,
    prepare,
    resolve_conventions,
)
from axiom.surface.nuisance import (
    AnyNuisanceTerm,
    EventIndicators,
    FourierSeasonality,
    LinearTrend,
    NuisanceSet,
    NuisanceTerm,
)
from axiom.surface.optimize import Allocation, AllocationMethod, Objective, allocate

__all__ = [
    "CARRYOVERS",
    "GRID_VERSION",
    "KERNELS",
    "Allocation",
    "AllocationMethod",
    "AnyCarryover",
    "AnyKernel",
    "AnyNuisanceTerm",
    "AscentPath",
    "Bounds",
    "CarryoverKernel",
    "CarryoverRole",
    "Criterion",
    "DelayedCarryover",
    "Design",
    "EventIndicators",
    "ExponentialKernel",
    "FitResult",
    "FourierSeasonality",
    "Frontier",
    "GeometricCarryover",
    "HillKernel",
    "InterceptKind",
    "KernelRole",
    "LinearKernel",
    "LinearTrend",
    "LogisticKernel",
    "MarginalHorizon",
    "Method",
    "NoCarryover",
    "NuisanceSet",
    "NuisanceTerm",
    "Objective",
    "ParameterRole",
    "PowerKernel",
    "ResponseKernel",
    "StationaryPoint",
    "Surface",
    "SurfaceSpec",
    "WeibullCarryover",
    "a_criterion",
    "allocate",
    "bayesian_criterion",
    "box_behnken",
    "build",
    "canonical_analysis",
    "carryover_from_name",
    "central_composite",
    "check_linearization",
    "column_names",
    "counterfactual_doses",
    "d_criterion",
    "defining_relation",
    "design_matrix",
    "e_criterion",
    "equal_spacing",
    "fit",
    "forward",
    "fractional_factorial",
    "frontier",
    "full_factorial",
    "gradient",
    "hessian",
    "interaction_name",
    "kernel_from_name",
    "latin_hypercube",
    "linear_coefficients",
    "marginal",
    "marginal_expr",
    "marginal_total",
    "optimal_exchange",
    "parameter_roles",
    "predict",
    "predict_marginal",
    "prepare",
    "resolve_conventions",
    "steepest_ascent",
]
