"""The report template language: what it promises, and what it refuses."""

from __future__ import annotations

import importlib.util
import re
import zipfile

import numpy as np
import pandas as pd
import pytest

from axiom.core import D, Interval, LedgerLine, Unsupported, eti
from axiom.report import (
    FORMATS,
    Figure,
    Heading,
    Metric,
    PageBreak,
    Paragraph,
    Report,
    ReportBuilder,
    Section,
    Table,
    Theme,
    missing,
    placeholders,
    render,
    resolve,
    write,
)
from axiom.report.resolve import ResolvedFigure, ResolvedMetric, ResolvedText
from axiom.sim import DosePlan, surface_world
from axiom.surface import HillKernel, ResponseBand, fit, response_band
from axiom.viz import available

HAS_PPTX = importlib.util.find_spec("pptx") is not None
HAS_PDF = importlib.util.find_spec("reportlab") is not None
HAS_KALEIDO = importlib.util.find_spec("kaleido") is not None
static = pytest.mark.skipif(
    not (HAS_PPTX and HAS_PDF and HAS_KALEIDO), reason="the report extra is not installed"
)


@pytest.fixture(scope="module")
def band() -> ResponseBand:
    world = surface_world(
        n_units=3,
        n_periods=8,
        treatments=("a",),
        kernels=HillKernel(reference_dose=50.0, amplitude_scale=10.0),
        doses=DosePlan(scale=50.0, zero_fraction=0.2),
        intercept="shared",
        noise_sd=0.5,
        seed=1,
    )
    result = fit(world.spec, world.panel, backend="laplace", draws=80, chains=1, seed=1)
    built = response_band(result, "a", n_grid=6, mass=0.9)
    assert isinstance(built, ResponseBand)
    return built


@pytest.fixture
def template() -> Report:
    return (
        ReportBuilder("demo", "Readout")
        .subtitle("as of {as_of}")
        .footer("generated by axiom")
        .section("Headline", summary="Every number carries its interval.")
        .paragraph("The effect is **{effect:.1f}** units.")
        .metric("contrast", "Effect at 50", unit="units")
        .section("Curve")
        .figure("response", caption="With its {mass:.0%} band")
        .section("Detail")
        .table("arms")
        .ledger("ledger")
        .build()
    )


@pytest.fixture
def context(band: ResponseBand) -> dict[str, object]:
    return {
        "as_of": "2026-08-21",
        "effect": 7.25,
        "mass": 0.9,
        "contrast": eti(np.linspace(6.0, 8.0, 200), 0.9),
        "response": band,
        "arms": pd.DataFrame({"dose": [0.0, 25.0, 50.0], "outcome": [1.0, 4.5, 6.25]}),
        "ledger": [LedgerLine(kind="identification", statement="dose is randomized")],
    }


# -- the template language -----------------------------------------------------------------


def test_placeholders_are_parsed_not_guessed() -> None:
    assert placeholders("plain") == ()
    assert placeholders("{a} and {b:.2f} and {a}") == ("a", "b")
    assert placeholders("{{literal}} braces") == ()
    assert placeholders("{obj.field}") == ("obj",)
    with pytest.raises(ValueError, match="positional placeholders"):
        placeholders("{} unnamed")


def test_a_report_holds_no_data_only_the_names_of_data(template: Report) -> None:
    """The property that makes it a template: sources, in reading order, no values."""
    assert template.sources() == (
        "as_of",
        "effect",
        "contrast",
        "response",
        "mass",
        "arms",
        "ledger",
    )
    text = template.to_json()
    assert "2026-08-21" not in text and "7.25" not in text


def test_missing_names_every_absent_key_at_once(template: Report) -> None:
    assert missing(template, {}) == template.sources()
    assert missing(template, {"as_of": "x", "effect": 1.0}) == (
        "contrast",
        "response",
        "mass",
        "arms",
        "ledger",
    )


def test_the_same_template_renders_two_contexts_and_keeps_its_hash(
    template: Report, context: dict[str, object]
) -> None:
    """'Automated and repeated': layout is the template's identity, data is not."""
    first = resolve(template, context)
    second = resolve(template, {**context, "effect": 9.5, "as_of": "2026-11-01"})
    assert not isinstance(first, Unsupported) and not isinstance(second, Unsupported)
    assert first.source_hash == second.source_hash == template.content_hash()
    assert first.sections[0].blocks[0] != second.sections[0].blocks[0]
    assert "7.2" in first.sections[0].blocks[0].text
    assert "9.5" in second.sections[0].blocks[0].text


def test_a_missing_source_is_a_typed_failure_not_an_exception(template: Report) -> None:
    out = resolve(template, {"as_of": "x"})
    assert isinstance(out, Unsupported)
    assert "contrast" in out.reason and "ledger" in out.reason
    assert out.missing == missing(template, {"as_of": "x"})


def test_a_present_but_unusable_source_names_the_block(context: dict[str, object]) -> None:
    """A gap in the data is Unsupported; a mistake in the template is an exception."""
    report = Report(
        name="r", title="t", sections=(Section(title="s", blocks=(Figure(source="arms"),)),)
    )
    with pytest.raises(ValueError, match="figure block 'arms' needs a plotly Figure"):
        resolve(report, context)
    report = Report(
        name="r",
        title="t",
        sections=(Section(title="s", blocks=(Metric(source="arms", label="x"),)),),
    )
    with pytest.raises(ValueError, match="metric block 'arms' needs a number"):
        resolve(report, context)
    report = Report(
        name="r", title="t", sections=(Section(title="s", blocks=(Table(source="effect"),)),)
    )
    with pytest.raises(ValueError, match="table block 'effect' needs a DataFrame"):
        resolve(report, {"effect": 1.0})


def test_a_table_truncates_loudly(context: dict[str, object]) -> None:
    block = Table(source="arms", max_rows=2)
    report = Report(name="r", title="t", sections=(Section(title="s", blocks=(block,)),))
    out = resolve(report, context)
    assert not isinstance(out, Unsupported)
    table = out.sections[0].blocks[0]
    assert len(table.rows) == 2
    assert table.truncated == 1
    with pytest.raises(ValueError, match="has no column"):
        resolve(
            Report(
                name="r",
                title="t",
                sections=(Section(title="s", blocks=(Table(source="arms", columns=("nope",)),)),),
            ),
            context,
        )


def test_page_breaks_become_positions_not_blocks() -> None:
    report = Report(
        name="r",
        title="t",
        sections=(
            Section(
                title="s",
                blocks=(Paragraph(text="a"), PageBreak(), Paragraph(text="b")),
            ),
        ),
    )
    out = resolve(report, {})
    assert not isinstance(out, Unsupported)
    assert len(out.sections[0].blocks) == 2
    assert out.sections[0].breaks == frozenset({1})


# -- uncertainty is not a rendering option --------------------------------------------------


def test_a_surface_figure_carries_its_band(template: Report, context: dict[str, object]) -> None:
    """A ResponseBand source is drawn through viz, which cannot draw one without its band."""
    out = resolve(template, context)
    assert not isinstance(out, Unsupported)
    figure = next(b for s in out.sections for b in s.blocks if isinstance(b, ResolvedFigure))
    assert len(figure.figure.data) == 2
    assert figure.figure.data[0].fill == "toself"
    assert "90%" in figure.caption


@pytest.mark.parametrize(
    ("value", "has_interval"),
    [
        (eti(np.linspace(0.0, 2.0, 100), 0.9), True),
        (3.5, False),
    ],
)
def test_a_metric_shows_its_interval_when_it_has_one(value: object, has_interval: bool) -> None:
    report = Report(
        name="r",
        title="t",
        sections=(Section(title="s", blocks=(Metric(source="v", label="Effect", unit="mmHg"),)),),
    )
    out = resolve(report, {"v": value})
    assert not isinstance(out, Unsupported)
    metric = out.sections[0].blocks[0]
    assert isinstance(metric, ResolvedMetric)
    assert metric.unit == "mmHg" and "mmHg" in metric.text
    if has_interval:
        assert isinstance(metric.interval, Interval)
        assert "90%" in metric.interval_text and "ETI" in metric.interval_text
    else:
        assert metric.interval is None and metric.interval_text == ""


def test_a_summary_and_an_estimand_result_both_keep_their_interval() -> None:
    from axiom.core import summarize

    summary = summarize(np.linspace(1.0, 3.0, 200), definition="hdi", mass=0.8)
    report = Report(
        name="r", title="t", sections=(Section(title="s", blocks=(Metric(source="v", label="L"),)),)
    )
    out = resolve(report, {"v": summary})
    assert not isinstance(out, Unsupported)
    metric = out.sections[0].blocks[0]
    assert metric.interval is not None
    assert metric.interval.mass == 0.8 and metric.interval.definition == "hdi"


def test_nothing_in_the_block_vocabulary_can_suppress_an_interval() -> None:
    """There is no field anywhere that turns uncertainty off. That is the point."""
    forbidden = {"show_interval", "with_interval", "hide_interval", "band", "show_band"}
    for cls in (Metric, Figure, Table, Paragraph, Heading):
        assert not forbidden & set(cls.model_fields), cls.__name__


def test_the_theme_cannot_hide_a_band() -> None:
    with pytest.raises(ValueError):
        Theme(band_opacity=0.0)
    assert Theme(band_opacity=0.05).band_opacity == 0.05


# -- rendering ------------------------------------------------------------------------------


@pytest.mark.skipif(not available(), reason="plotly not installed")
def test_html_is_self_contained_and_interactive(
    template: Report, context: dict[str, object]
) -> None:
    html = render(template, context, "html")
    assert isinstance(html, str)
    assert html.startswith("<!DOCTYPE html>")
    assert "Plotly.newPlot" in html, "plotly.js is inlined so the file opens offline"
    assert html.count('class="plotly-graph-div"') == 1
    assert '"fill":"toself"' in html, "the band survives into the document"
    assert re.search(r'class="interval">\[[^<]+\(90% ETI\)', html)
    assert template.content_hash() in html, "the template's identity travels with the output"
    assert "dose is randomized" in html


@pytest.mark.skipif(not available(), reason="plotly not installed")
def test_html_can_use_the_cdn_instead_of_inlining(
    template: Report, context: dict[str, object]
) -> None:
    inlined = render(template, context, "html", inline_plotly=True)
    linked = render(template, context, "html", inline_plotly=False)
    assert isinstance(inlined, str) and isinstance(linked, str)
    assert len(linked) < len(inlined) / 10


@static
def test_pptx_has_a_slide_per_section_and_embeds_its_figures(
    template: Report, context: dict[str, object], tmp_path
) -> None:  # type: ignore[no-untyped-def]
    out = write(template, context, str(tmp_path / "r.pptx"))
    assert isinstance(out, str)
    with zipfile.ZipFile(out) as archive:
        slides = [n for n in archive.namelist() if re.match(r"ppt/slides/slide\d+\.xml$", n)]
        images = [n for n in archive.namelist() if n.startswith("ppt/media/")]
        text = " ".join(re.sub(r"<[^>]+>", " ", archive.read(name).decode()) for name in slides)
    assert len(slides) >= 4, "a title slide and at least one per section"
    assert len(images) == 1, "the figure is rasterised into the deck"
    assert "90% ETI" in text, "the interval reaches the slide"
    for title in ("Headline", "Curve", "Detail"):
        assert title in text


@static
def test_pdf_is_paged_and_embeds_its_figures(
    template: Report, context: dict[str, object], tmp_path
) -> None:  # type: ignore[no-untyped-def]
    out = write(template, context, str(tmp_path / "r.pdf"))
    assert isinstance(out, str)
    raw = (tmp_path / "r.pdf").read_bytes()
    assert raw.startswith(b"%PDF")
    assert raw.count(b"/Type /Page") + raw.count(b"/Type/Page") >= 3
    assert raw.count(b"/Subtype /Image") + raw.count(b"/Subtype/Image") >= 1


@static
def test_pdf_table_cells_wrap_instead_of_running_over_the_next_column(
    tmp_path,
) -> None:  # type: ignore[no-untyped-def]
    """reportlab does not wrap a bare string: it draws it at full width.

    A table of sentences -- an assumption ledger, a provenance appendix -- was
    rendered as overlapping text, each column smeared across the next. Cells are
    ``Paragraph`` s now, so a long cell grows downwards instead.

    The observable consequence, without needing a PDF parser: a table of long
    sentences is much taller than the same table of short ones, and overflows
    onto further pages. Unwrapped, every row is one line and it never would.
    """

    def pages(rows: list[dict[str, str]], name: str) -> int:
        report = Report(
            name="t",
            title="Wrapping",
            sections=(Section(title="Assumptions", blocks=(Table(source="rows"),)),),
        )
        out = write(report, {"rows": rows}, str(tmp_path / name))
        assert isinstance(out, str), out
        raw = (tmp_path / name).read_bytes()
        return raw.count(b"/Type /Page") + raw.count(b"/Type/Page")

    long_row = {
        "Assumption": "no unmeasured confounding",
        "Statement": "age is the only common cause of dose and systolic pressure in "
        "the population the trial enrolled from",
        "Challenged by": "a sensitivity analysis at plausible confounder strength, "
        "reported on the decision scale rather than the coefficient scale",
    }
    short_row = {"Assumption": "a", "Statement": "b", "Challenged by": "c"}

    assert pages([short_row] * 30, "short.pdf") <= 2
    assert pages([long_row] * 30, "long.pdf") > 2, "long cells did not wrap"


def test_write_infers_the_format_and_refuses_a_suffix_it_cannot(
    template: Report, context: dict[str, object], tmp_path
) -> None:  # type: ignore[no-untyped-def]
    with pytest.raises(ValueError, match="cannot infer a format"):
        write(template, context, str(tmp_path / "r.docx"))
    with pytest.raises(ValueError, match="unknown format"):
        render(template, context, "latex")  # type: ignore[arg-type]


def test_rendering_without_the_context_refuses_before_it_draws_anything(
    template: Report,
) -> None:
    for fmt in FORMATS:
        out = render(template, {}, fmt)
        assert isinstance(out, Unsupported)
        assert out.missing == template.sources()


# -- the builder ----------------------------------------------------------------------------


def test_the_builder_is_immutable_and_composes() -> None:
    base = ReportBuilder("r", "T").section("One")
    left = base.paragraph("left")
    right = base.paragraph("right")
    assert left.build().sections[0].blocks[0].text == "left"
    assert right.build().sections[0].blocks[0].text == "right"
    assert base.build().sections[0].blocks == ()


def test_the_builder_refuses_a_block_with_no_section() -> None:
    with pytest.raises(ValueError, match="open a section before adding blocks"):
        ReportBuilder("r", "T").paragraph("orphan")
    with pytest.raises(ValueError, match="at least one section"):
        ReportBuilder("r", "T").build()


def test_a_report_refuses_duplicate_section_titles() -> None:
    with pytest.raises(ValueError, match="duplicate section title"):
        ReportBuilder("r", "T").section("Same").paragraph("a").section("Same").build()


def test_a_bad_placeholder_fails_when_the_template_is_built_not_when_it_renders() -> None:
    with pytest.raises(ValueError, match="positional placeholders"):
        Paragraph(text="{} unnamed")
    with pytest.raises(ValueError, match="positional placeholders"):
        ReportBuilder("r", "T").section("s").paragraph("{}").build()


# -- specs ----------------------------------------------------------------------------------


def test_report_and_theme_round_trip(template: Report) -> None:
    assert Report.from_dict(template.to_dict()) == template
    assert Report.from_json(template.to_json()) == template
    theme = Theme(name="house", accent_color="#123456", palette=("#111111", "#222222"))
    assert Theme.from_dict(theme.to_dict()) == theme
    # restyling is a different report, and the hash says so
    assert template.model_copy(update={"theme": theme}).content_hash() != template.content_hash()


def test_theme_validates_its_colours_and_geometry() -> None:
    with pytest.raises(ValueError, match="hex colour"):
        Theme(accent_color="blue")
    with pytest.raises(ValueError, match="palette colours"):
        Theme(palette=("#fff",))
    with pytest.raises(ValueError, match="page must be a paper size"):
        Theme(page="widescreen")
    with pytest.raises(ValueError, match="slide must be a slide size"):
        Theme(slide="a4")
    theme = Theme()
    assert theme.page_geometry() == (612.0, 792.0)
    assert theme.slide_geometry() == (960.0, 540.0)
    assert theme.heading_size(1) > theme.heading_size(3)
    assert theme.heading_size(9) == theme.heading_size(3)
    assert theme.colour(0) == theme.colour(len(theme.palette))


def test_resolved_text_distinguishes_headings(context: dict[str, object]) -> None:
    report = Report(
        name="r",
        title="t",
        sections=(Section(title="s", blocks=(Heading(text="H", level=1), Paragraph(text="p"))),),
    )
    out = resolve(report, context)
    assert not isinstance(out, Unsupported)
    heading, paragraph = out.sections[0].blocks
    assert isinstance(heading, ResolvedText) and heading.is_heading and heading.level == 1
    assert isinstance(paragraph, ResolvedText) and not paragraph.is_heading


def test_dimensions_are_untouched_by_reporting(band: ResponseBand) -> None:
    """A band keeps its dimension through a report; nothing here rescales a number."""
    assert band.dimension == D.outcome
    report = Report(
        name="r", title="t", sections=(Section(title="s", blocks=(Figure(source="b"),)),)
    )
    out = resolve(report, {"b": band})
    assert not isinstance(out, Unsupported)
    assert band.dimension == D.outcome
